spring:
  application:
    name: online_courses_management
  datasource:
    url: jdbc:postgresql://localhost:5432/online_courses_management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true